# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_dashboard:
    pattern: /dashboard
    defaults: { _controller: sylius.controller.backend:dashboardAction }

sylius_backend_user:
    resource: @SyliusWebBundle/Resources/config/routing/backend/user.yml
    prefix: /users

sylius_backend_product:
    resource: @SyliusWebBundle/Resources/config/routing/backend/product.yml
    prefix: /products

sylius_backend_stockable:
    resource: @SyliusWebBundle/Resources/config/routing/backend/stockable.yml
    prefix: /stockables

sylius_backend_variant:
    resource: @SyliusWebBundle/Resources/config/routing/backend/variant.yml
    prefix: /products/{productId}/variants

sylius_backend_option:
    resource: @SyliusWebBundle/Resources/config/routing/backend/option.yml
    prefix: /options

sylius_backend_property:
    resource: @SyliusWebBundle/Resources/config/routing/backend/property.yml
    prefix: /properties

sylius_backend_prototype:
    resource: @SyliusWebBundle/Resources/config/routing/backend/prototype.yml
    prefix: /prototypes

sylius_backend_taxonomy:
    resource: @SyliusWebBundle/Resources/config/routing/backend/taxonomy.yml
    prefix: /taxonomies

sylius_backend_taxon:
    resource: @SyliusWebBundle/Resources/config/routing/backend/taxon.yml
    prefix: /taxonomies/{taxonId}/taxons

sylius_backend_order:
    resource: @SyliusWebBundle/Resources/config/routing/backend/order.yml
    prefix: /orders

sylius_backend_promotion:
    resource: @SyliusWebBundle/Resources/config/routing/backend/promotion.yml
    prefix: /promotions

sylius_backend_promotion_rule:
    resource: @SyliusWebBundle/Resources/config/routing/backend/promotion_rule.yml
    prefix: /promotion-rules

sylius_backend_promotion_action:
    resource: @SyliusWebBundle/Resources/config/routing/backend/promotion_action.yml
    prefix: /promotion-actions

sylius_backend_tax_category:
    resource: @SyliusWebBundle/Resources/config/routing/backend/tax_category.yml
    prefix: /tax-categories

sylius_backend_tax_rate:
    resource: @SyliusWebBundle/Resources/config/routing/backend/tax_rate.yml
    prefix: /tax-rates

sylius_backend_shipping_category:
    resource: @SyliusWebBundle/Resources/config/routing/backend/shipping_category.yml
    prefix: /shipping-categories

sylius_backend_shipping_method:
    resource: @SyliusWebBundle/Resources/config/routing/backend/shipping_method.yml
    prefix: /shipping-methods

sylius_backend_country:
    resource: @SyliusWebBundle/Resources/config/routing/backend/country.yml
    prefix: /countries

sylius_backend_province:
    resource: @SyliusWebBundle/Resources/config/routing/backend/province.yml
    prefix: /provinces

sylius_backend_zone:
    resource: @SyliusWebBundle/Resources/config/routing/backend/zone.yml
    prefix: /zones

sylius_backend_zone_member:
    resource: @SyliusWebBundle/Resources/config/routing/backend/zone_member.yml
    prefix: /zone-members

sylius_backend_settings:
    resource: @SyliusWebBundle/Resources/config/routing/backend/settings.yml
    prefix: /settings
