# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_backend_dashboard:
    pattern: /dashboard
    defaults: { _controller: sylius.controller.backend:dashboardAction }

sylius_backend_tax_category:
    resource: @SyliusWebBundle/Resources/config/routing/backend/tax_category.yml
    prefix: /tax-categories

sylius_backend_tax_rate:
    resource: @SyliusWebBundle/Resources/config/routing/backend/tax_rate.yml
    prefix: /tax-rates
