# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_frontend:
    resource: @SyliusWebBundle/Resources/config/routing/frontend/main.yml

sylius_backend:
    resource: @SyliusWebBundle/Resources/config/routing/backend/main.yml
    prefix: /administration
